server:
  port: 8888

spring:
  thymeleaf:
    #关闭模板缓存(默认为true)
    cache: false
    #模板编码
    encoding: utf-8
    #在构建URL时添加到视图名称前的前缀（默认值：classpath:/templates/）
    prefix: classpath:/templates/
    #在构建URL时添加到视图名称后的后缀（默认值：.html）
    suffix: .html
    mode: HTML5
    check-template-location: true
#  datasource:
#    driver-class-name: org.sqlite.JDBC
#    url: jdbc:sqlite::resource:static/sqlite/hearthstone.sqlite
#mybatis:
#  mapper-locations: classpath:static/mapper/*.xml
logging:
  config: classpath:config/logback-spring.xml
log:
  level: info
  path: C:/ProgramData/hs_script/log

game:
  name: "炉石传说"
  properties:
    path: C:/ProgramData/hs_script
    name: /game.properties
  log:
    path:
      screen: /Logs/LoadingScreen.log
      power: /Logs/Power.log
#      获取程序标题的命令
command:
  title: "Get-Process |where {$_.mainWindowTitle} |format-table id, name,mainwindowtitle -AutoSize"
platform:
  name: "战网"
script:
  name: "炉石传说脚本"