game:
  log:
    configuration:
      path: ${LOCALAPPDATA:}/Blizzard/Hearthstone/log.config
    out:
      path: /Logs/
      file:
        screen: /LoadingScreen.log
        power: /Power.log
        deck: /Decks.log

script:
  version: '@project.version@'
  path: ./
  resource: ${script.path}resource/
  configuration:
    path: ${script.path}config/
    file: ${script.configuration.path}script.ini

logging:
  level:
    root: info
  config: classpath:logback.xml

log:
  level: ${logging.level.root}
  path: ${script.path}
